title: "[質問]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        ## タイトルについて
        タイトルには質問したい内容をできるだけ具体的に書いてください！
        ### 例
        ```
          - Realmに保存した画像のパスを画像に変換できない
          - CollectionViewのCell内に、画面を長押ししたら画像が表示されるようにしたい
          - 変更したimageviewとlabelのデータをアプリを再起動しても変更した情報が残っているようにしたい
        ```
  - type: textarea
    id: what
    attributes:
      label: エラーの概要
      description: エラーの概要について教えて下さい！
      placeholder: 例：Realmに保存した画像のパスを画像に変換できない
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: 自分で調べた資料
      description: 自分で調べた資料のURLを貼ってください！
      placeholder: UIImageViewがタップされた時にイベントをつける(https://qiita.com/tanaka-tt/items/df1ebcc68f29e50c13c9)
  - type: textarea
    id: images
    attributes:
      label: エラーのスクリーンショット
      description: エラーが発生していることを表すスクーンショット(コンソールの出力など)を添付してください！
      placeholder: ここにスクリーンショットをドラッグ＆ドロップ
  - type: textarea
    id: other
    attributes:
      label: その他補足
      description: その他補足があれば記入お願いします！
      placeholder: その他
    validations:
      required: false
  - type: input
    id: github-url
    attributes:
      label: GitHubのURL
      description: | 
        GitHubのリポジトリを教えて下さい！
        かならず該当するコードがアップロードされていることを確認してください！
      placeholder: https://github.com/username/repository-name
    validations:
      required: true
  - type: checkboxes
    id: confirmation
    attributes:
      label: TODOリスト
      description: 最後に以下の作業を行ったか確認お願いします！
      options:
        - label: GitHubに最新のコードをアップロードしました。
        - label: できるだけ具体的なタイトルを設定しました。

