name: "onDiscussionCreated"
on:
  discussion:
    types: [created]
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: "escape json"
        run: |
          sed 's/'\''/'\\\\\''/g' ${{ github.event }} >> $PAYLOAD
      - name: "Send notification"
        run: |
          curl -i -H 'Content-Type: application/json' -d '${{ env.EVENT }}' -L '${{ env.ON_DISCUSSION_CREATED_URL }}'
        env:
          EVENT: ${{ toJSON(github.event) }}
          ON_DISCUSSION_CREATED_URL: ${{ secrets.ON_DISCUSSION_CREATED_URL }}
