name: "onDiscussionCreated"
on:
  discussion:
    types: [created]
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: "Send notification"
        run: |
          curl -v -H 'Content-Type: application/json' -d '${{ env.EVENT }}' -L '${{ env.ON_DISCUSSION_CREATED_URL }}'
        env:
          EVENT: ${{ toJson(github.event) }}
          ON_DISCUSSION_CREATED_URL: ${{ secrets.ON_DISCUSSION_CREATED_URL }}
